{% set version = "1.0.5" %}
{% set sha256 = "f8475829afef57c4ee08cc0ff649010a6529619064de439d42c0b6a24ef24d09" %}
{% set sip_version = "4.19.25" %}
{% set sip_sha256 = "b39d93e937647807bac23579edbff25fe46d16213f708370072574ab1f1b4211" %}
# curl -sL https://github.com/rpalovics/Alpenglow/archive/vX.X.X.tar.gz | openssl sha256

package:
  name: alpenglow
  version: {{ version }}

source:
  - url:  https://www.riverbankcomputing.com/static/Downloads/sip/{{ sip_version }}/sip-{{ sip_version }}.tar.gz
    sha256: {{ sip_sha256 }}
    folder: sip
    patches:
      - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
  - url: https://github.com/rpalovics/Alpenglow/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: alpenglow

build:
  skip: True  # [py<35]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make  # [not win]
  host:
    - python
    - setuptools
    - eigen
    - numpy
    - pip
  run:
    - python
    - pandas
    - numpy

test:
  imports:
    - alpenglow
    - alpenglow.experiments
    - alpenglow.evaluation
    - alpenglow.utils
    - alpenglow.offline
    - alpenglow.offline.models
    - alpenglow.offline.evaluation
    - alpenglow.cpp

about:
  home: https://github.com/rpalovics/Alpenglow
  summary: Open Source Recommender Framework with Time-aware Learning and Evaluation
  license: Apache-2.0
  license_file:
    - alpenglow/LICENSE
    - sip/LICENSE
  doc_url: http://alpenglow.readthedocs.io/

extra:
  recipe-maintainers:
    - proto-n
