{% set version = "0.1.8" %}
{% set sha256 = "09a08426fb439c8af85524ecf0542f985577dfb908cae4d48f035e08fd7285a8" %}

package:
  name: alpenglow
  version: {{ version }}

source:
  url: https://github.com/rpalovics/Alpenglow/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<35]
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - sip
    - setuptools
    - eigen
    - numpy

  run:
    - python
    - pandas
    - numpy
    - sip

test:
  imports:
    - alpenglow
    - alpenglow.experiments
    - alpenglow.evaluation
    - alpenglow.utils
    - alpenglow.offline
    - alpenglow.offline.models
    - alpenglow.offline.evaluation
    - alpenglow.cpp

about:
  home: https://github.com/rpalovics/Alpenglow
  summary: Open Source Recommender Framework with Time-aware Learning and Evaluation
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://alpenglow.readthedocs.io/

extra:
  recipe-maintainers:
    - proto-n
