{% set version = "0.1.7" %}
{% set sha256 = "609b0cb33cf9dc658b065a6831f3132f596c5723e03e54a1b73a232dbdcb15bb" %}

package:
  name: alpenglow
  version: {{ version }}

source:
  url: https://github.com/rpalovics/Alpenglow/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<35]
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - sip
    - setuptools
    - toolchain

  run:
    - python
    - pandas
    - numpy
    - sip

test:
  imports:
    - alpenglow
    - alpenglow.experiments
    - alpenglow.evaluation
    - alpenglow.utils
    - alpenglow.offline
    - alpenglow.offline.models
    - alpenglow.offline.evaluation
    - alpenglow.cpp

about:
  home: https://github.com/rpalovics/Alpenglow
  summary: Open Source Recommender Framework with Time-aware Learning and Evaluation
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://alpenglow.readthedocs.io/

extra:
  recipe-maintainers:
    - proto-n
