{% set version = "1.0.1" %}
{% set sha256 = "b4534cacd8bee6b3d5e1b3d0a544bb8498cf1972118eeeaf7f90b802f138c595" %}
# curl -sL https://github.com/rpalovics/Alpenglow/archive/vX.X.X.tar.gz | openssl sha256

package:
  name: alpenglow
  version: {{ version }}

source:
  url: https://github.com/rpalovics/Alpenglow/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<35]
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - sip
    - setuptools
    - eigen
    - numpy
  run:
    - python
    - pandas
    - numpy
    - sip

test:
  imports:
    - alpenglow
    - alpenglow.experiments
    - alpenglow.evaluation
    - alpenglow.utils
    - alpenglow.offline
    - alpenglow.offline.models
    - alpenglow.offline.evaluation
    - alpenglow.cpp

about:
  home: https://github.com/rpalovics/Alpenglow
  summary: Open Source Recommender Framework with Time-aware Learning and Evaluation
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://alpenglow.readthedocs.io/

extra:
  recipe-maintainers:
    - proto-n
