travis:
  secure:
    BINSTAR_TOKEN: bmGw9jNAVSg0UCkDyyLUSwhJOoEJQT/9zjm+q/lXhBfdnasRCMeArDX8JRdfyQuryBVjtbm324RnY/3apt5VPBF8ybbMafAX+56fAD13FZintNpJDuBHZ66iNV5rCLqkMpTVi+2nQezaYkt0DGGp848HzC904xe9XNECIXI/jvBk8S2gsLfSHivnovTzJIiPqpDEFNWXb360mRCI6m17LAMEnd5S2pXkqS4y6e7bqidLJvJvgN1hebN/I3gUIHE+FsIKx6nFhqv5U9Xs/bhBYC+R4MGPb2lM4X9IDKcFWqGq6Q//eDMNG57VfvrvdlBEsWDoWtVBw7LRgUeQKOKUbyQmdvF2ExHaM9Dfr7DfjOZGBnYqxxElhLbbdHlaI49M15Q5mQCbhrgE2o8Mat0lOBfLqQI0fkOi/YUXZd/sunqZ4Uxp7u70biTocqYpRakE96v3gSyGa0NaoyNmslX/VrC4YGngr2SDLTQ6vJFBSYYNwI5nOnLXOrooxsPx9bILaTMaNT+T+PiQUdjlf/xOkHpTGbXobH802ni86vgaBr4PJrchkXmuWabsK6bNDmswTjHXQqCUdb+Vc1XyjUGJ6VscKJUK6Moy7ngL/sARYnFwgMryMh8/x8PQ41e44VJVDyUoN4CZJsSL9sYSp6fxPGOLWMMJOn6Fx6bRMc296l4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
