travis:
  secure:
    BINSTAR_TOKEN: p5jHt9bCJc+JpzLgh99hrj+Xa2lxEFM4t0QtWMQCR/XQCP0uDHarBNBFPL572+NRvsc4awbkVgIwjY4H24j+c8IBsh2SUz1HR1LdGDI78zUFBw8mqy9oys4tvv2nsjxBmZNNCPmfytrORxCe+y1s9grmolqr7boIeQHwpaqGxpPgTFs6+7aG3bXAfwz6MfyabooOAH7MIpb5+hdw+REhQ/8XoGZhiah9brEdVR0y90mcSZ/TDQYB+zblOUYZCZl8hQL9Y8sHIWFNs5J783uqU0RFwQTc3Q2KqwznILQbzpqe7HBoLYmVDsGOqtN3okV7ZhBryDKlhlc88o+rwpW9+jwkVVR28/vjfjZwnmggRy9xqQ9JoTg9yKV2f7hmNEqaqYCJ5ZA91snKSXKRTjCr5EKktdz+jeQQMHwFQ+/iZ0Yxbg8UUYB/zmEmUZk4p20DFyo80VDWHjyV0n25/hhnDeGxnJtucHcaUZR1Oar6VOuCHcdea+XcErWufD5RtTqHCgKN+cavxjB4xPOGSO+0owPxDUNC5l+jJRPU7LE+xp89zC5oUPpJhpiNAkj1QtIvYZfQSm4GPAg9Uo0wtCCQQNVn+TJ7vr0vTY2egnL1dMkPD5wHkk8AJSJ9pqIRrMh73OrVVccpaJYYsD1BjpoxKjYrRXqHaDCSwOZ9b31BTAg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
